name: Deploy Next.js to GitHub Pages

on:
  push:
    branches: [ main ]   # 필요 시 변경
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      # 환경변수가 필요한 경우 여기에 주입 (예: NEXT_PUBLIC_*)
      # - name: Inject env
      #   run: |
      #     echo "NEXT_PUBLIC_API_BASE=${{ secrets.NEXT_PUBLIC_API_BASE }}" >> $GITHUB_ENV

      - name: Build
        run: npm run build

      - name: Static export
        run: npm run export

      # GitHub Pages는 공식 pages action을 권장합니다.
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./out

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
